<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>no.nav.regoppslag</groupId>
	<artifactId>regoppslag</artifactId>
	<packaging>pom</packaging>
	<version>0.0.28-SNAPSHOT</version>
	<name>regoppslag</name>

	<prerequisites>
		<maven>3.3.9</maven>
	</prerequisites>

	<scm>
		<connection>scm:git:http://stash.devillo.no/scm/boaf/regoppslag.git</connection>
		<developerConnection>scm:git:http://stash.devillo.no/scm/boaf/regoppslag.git</developerConnection>
		<url>http://stash.devillo.no/projects/BOAF/repos/regoppslag</url>
		<tag>HEAD</tag>
	</scm>

	<modules>
		<module>app</module>
	</modules>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.10.RELEASE</version>
	</parent>


	<distributionManagement>
		<repository>
			<id>m2internal</id>
			<name>NAV Internal Repository</name>
			<url>dav:http://maven.adeo.no/nexus/content/repositories/m2internal</url>
		</repository>
		<snapshotRepository>
			<id>m2snapshot</id>
			<name>NAV Snapshot Repository</name>
			<url>dav:http://maven.adeo.no/nexus/content/repositories/m2snapshot</url>
		</snapshotRepository>
	</distributionManagement>

	<properties>
		<additionalparam>-Xdoclint:none</additionalparam>
		<spring.v>1.5.10.RELEASE</spring.v>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<lombok.version>1.16.20</lombok.version>
		<bootstrap.version>3.3.6</bootstrap.version>
		<retry.version>1.0.2.RELEASE</retry.version>
		<javax.servlet-api.version>3.1.0</javax.servlet-api.version>
		<prometheus.version>0.3.0</prometheus.version>
		<cxf.version>3.2.2</cxf.version>
		<nav-person-v3-tjenestespesifikasjon.version>3.0.2</nav-person-v3-tjenestespesifikasjon.version>
		<nav-fim-organisasjon-v4-tjenestespesifikasjon.version>1.0.4</nav-fim-organisasjon-v4-tjenestespesifikasjon.version>
		<organisasjonenhetkontaktinformasjon-v1-tjenestespesifikasjon.version>1.1.0</organisasjonenhetkontaktinformasjon-v1-tjenestespesifikasjon.version>
		<dokkat-api.version>9.4.1</dokkat-api.version>
		<modig-security.version>3.0.6</modig-security.version>
		<modig-log-common.version>1.1.3</modig-log-common.version>
		<wiremock-standalone.version>2.15.0</wiremock-standalone.version>
		<modig-testcertificates.version>1.2.0</modig-testcertificates.version>
		<rxjava.version>2.1.9</rxjava.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.webjars</groupId>
				<artifactId>bootstrap</artifactId>
				<version>${bootstrap.version}</version>
			</dependency>

			<dependency>
				<groupId>net.logstash.logback</groupId>
				<artifactId>logstash-logback-encoder</artifactId>
				<version>4.10</version>
			</dependency>
			<dependency>
				<groupId>javax.inject</groupId>
				<artifactId>javax.inject</artifactId>
				<version>1</version>
			</dependency>
			<dependency>
				<groupId>javax.servlet</groupId>
				<artifactId>javax.servlet-api</artifactId>
				<version>${javax.servlet-api.version}</version>
			</dependency>
			<!-- Provided dependencies -->
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
				<scope>provided</scope>
			</dependency>
			<!-- Test dependencies -->
			<dependency>
				<groupId>com.github.tomakehurst</groupId>
				<artifactId>wiremock-standalone</artifactId>
				<version>${wiremock-standalone.version}</version>
				<scope>test</scope>
			</dependency>

			<!--CXF dependencies-->
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-spring-boot-starter-jaxws</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-frontend-jaxws</artifactId>
				<version>${cxf.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>

		<!-- Logging dependecies -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-logging</artifactId>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.retry</groupId>
			<artifactId>spring-retry</artifactId>
			<version>${retry.version}</version>
		</dependency>
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
	</dependencies>


	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-webdav-jackrabbit</artifactId>
				<version>1.0</version>
			</extension>
		</extensions>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.20.1</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>2.20.1</version>
				<configuration>
					<additionalClasspathElements>${basedir}/target/classes</additionalClasspathElements>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>1.5.10.RELEASE</version>
				<configuration>
					<skip>false</skip>
					<fork>true</fork>
					<useTestClasspath>true</useTestClasspath>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
						<configuration>
							<finalName>app</finalName>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>