<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>no.nav.regoppslag</groupId>
	<artifactId>regoppslag</artifactId>
	<packaging>pom</packaging>
	<version>1-SNAPSHOT</version>
	<name>regoppslag</name>

	<scm>
		<connection>scm:git:https://stash.adeo.no/scm/boaf/regoppslag.git</connection>
		<developerConnection>scm:git:https://stash.adeo.no/scm/boaf/regoppslag.git</developerConnection>
		<url>https://stash.adeo.no/projects/BOAF/repos/regoppslag</url>
		<tag>HEAD</tag>
	</scm>

	<modules>
		<module>app</module>
	</modules>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.5</version>
	</parent>

	<distributionManagement>
		<repository>
			<id>m2internal</id>
			<name>NAV Internal Repository</name>
			<url>dav:http://maven.adeo.no/nexus/content/repositories/m2internal</url>
		</repository>
		<snapshotRepository>
			<id>m2snapshot</id>
			<name>NAV Snapshot Repository</name>
			<url>dav:http://maven.adeo.no/nexus/content/repositories/m2snapshot</url>
		</snapshotRepository>
	</distributionManagement>

	<properties>
		<java.version>11</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<additionalparam>-Xdoclint:none</additionalparam>
		<bootstrap.version>4.5.0</bootstrap.version>
		<resilience4j.version>0.13.1</resilience4j.version>
		<cxf.version>3.4.0</cxf.version>
		<wss4j-ws-security-dom.version>2.2.4</wss4j-ws-security-dom.version>
		<nav-person-v3-tjenestespesifikasjon.version>3.0.2</nav-person-v3-tjenestespesifikasjon.version>
		<nav-fim-organisasjon-v4-tjenestespesifikasjon.version>1.0.4</nav-fim-organisasjon-v4-tjenestespesifikasjon.version>
		<organisasjonenhetkontaktinformasjon-v1-tjenestespesifikasjon.version>1.1.0
		</organisasjonenhetkontaktinformasjon-v1-tjenestespesifikasjon.version>
		<pesysbrev01.version>1.0.44</pesysbrev01.version>
		<dokkat-api.version>9.4.1</dokkat-api.version>
		<modig-security.version>3.0.6</modig-security.version>
		<modig-log-common.version>1.1.3</modig-log-common.version>
		<rxjava.version>2.1.14</rxjava.version>
		<kryo.version>4.0.2</kryo.version>
		<brevdata-felles.version>0.0.10</brevdata-felles.version>
		<javax.inject.version>1</javax.inject.version>
		<springfox-swagger2.version>2.10.0</springfox-swagger2.version>
		<jaxb-core.version>2.3.0.1</jaxb-core.version>
		<nv-i18n.version>1.26</nv-i18n.version>
		<logstash-logback-encoder.version>6.4</logstash-logback-encoder.version>
		<jakarta.jaxws-api.version>3.0.1</jakarta.jaxws-api.version>
		<jakarta.activation.version>2.0.1</jakarta.activation.version>
		<!-- test -->
		<modig-testcertificates.version>1.2.5</modig-testcertificates.version>
		<wiremock-standalone.version>2.25.1</wiremock-standalone.version>
		<httpunit.version>1.7</httpunit.version>
		<spring-cloud-contract-wiremock.version>2.1.4.RELEASE</spring-cloud-contract-wiremock.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>jakarta.activation</groupId>
				<artifactId>jakarta.activation-api</artifactId>
				<version>${jakarta.activation.version}</version>
			</dependency>
			<dependency>
				<groupId>org.webjars</groupId>
				<artifactId>bootstrap</artifactId>
				<version>${bootstrap.version}</version>
			</dependency>
			<dependency>
				<groupId>net.logstash.logback</groupId>
				<artifactId>logstash-logback-encoder</artifactId>
				<version>${logstash-logback-encoder.version}</version>
				<exclusions>
					<exclusion>
						<groupId>com.fasterxml.jackson.core</groupId>
						<artifactId>jackson-databind</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>javax.inject</groupId>
				<artifactId>javax.inject</artifactId>
				<version>${javax.inject.version}</version>
			</dependency>
			<dependency>
				<groupId>javax.servlet</groupId>
				<artifactId>javax.servlet-api</artifactId>
				<version>${servlet-api.version}</version>
			</dependency>
			<dependency>
				<groupId>jakarta.xml.ws</groupId>
				<artifactId>jakarta.xml.ws-api</artifactId>
				<version>${jakarta.jaxws-api.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.resilience4j</groupId>
				<artifactId>resilience4j-circuitbreaker</artifactId>
				<version>${resilience4j.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.resilience4j</groupId>
				<artifactId>resilience4j-timelimiter</artifactId>
				<version>${resilience4j.version}</version>
			</dependency>
			<dependency>
				<groupId>com.esotericsoftware</groupId>
				<artifactId>kryo</artifactId>
				<version>${kryo.version}</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger2</artifactId>
				<version>${springfox-swagger2.version}</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger-ui</artifactId>
				<version>${springfox-swagger2.version}</version>
			</dependency>
			<!--CXF dependencies-->
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-spring-boot-starter-jaxws</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-core</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.wss4j</groupId>
				<artifactId>wss4j-ws-security-dom</artifactId>
				<version>${wss4j-ws-security-dom.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.bind</groupId>
				<artifactId>jaxb-core</artifactId>
				<version>${jaxb-core.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.bind</groupId>
				<artifactId>jaxb-impl</artifactId>
				<version>${javax-jaxb.version}</version>
			</dependency>
			<dependency>
				<groupId>com.neovisionaries</groupId>
				<artifactId>nv-i18n</artifactId>
				<version>${nv-i18n.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.modig</groupId>
				<artifactId>modig-log-common</artifactId>
				<version>${modig-log-common.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.modig</groupId>
				<artifactId>modig-security-ws</artifactId>
				<version>${modig-security.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.modig</groupId>
				<artifactId>modig-security-loginmodule</artifactId>
				<scope>runtime</scope>
				<version>${modig-security.version}</version>
			</dependency>
			<!-- grensesnitt/kontrakter -->
			<dependency>
				<groupId>no.nav.tjenester</groupId>
				<artifactId>nav-person-v3-tjenestespesifikasjon</artifactId>
				<version>${nav-person-v3-tjenestespesifikasjon.version}</version>
				<classifier>jaxws</classifier>
			</dependency>
			<dependency>
				<groupId>no.nav.tjenester.fim</groupId>
				<artifactId>nav-fim-organisasjon-v4-tjenestespesifikasjon</artifactId>
				<version>${nav-fim-organisasjon-v4-tjenestespesifikasjon.version}</version>
				<classifier>jaxws</classifier>
			</dependency>
			<dependency>
				<groupId>no.nav.tjenester</groupId>
				<artifactId>nav-organisasjonEnhetKontaktinformasjon-v1-tjenestespesifikasjon</artifactId>
				<version>${organisasjonenhetkontaktinformasjon-v1-tjenestespesifikasjon.version}</version>
				<classifier>jaxws</classifier>
			</dependency>
			<dependency>
				<groupId>no.nav.dokkat</groupId>
				<artifactId>dokkat-api</artifactId>
				<version>${dokkat-api.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dok.metaforcemal</groupId>
				<artifactId>pesysbrev01</artifactId>
				<version>${pesysbrev01.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dok.metaforcemal</groupId>
				<artifactId>brevdata-felles</artifactId>
				<version>${brevdata-felles.version}</version>
			</dependency>
			<!-- Provided dependencies -->
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
				<scope>provided</scope>
			</dependency>
			<!-- Test dependencies -->
			<dependency>
				<groupId>junit</groupId>
				<artifactId>junit</artifactId>
				<version>${junit.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>com.github.tomakehurst</groupId>
				<artifactId>wiremock-standalone</artifactId>
				<version>${wiremock-standalone.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-core</artifactId>
				<version>${mockito.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.hamcrest</groupId>
				<artifactId>hamcrest-library</artifactId>
				<version>${hamcrest.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.hamcrest</groupId>
				<artifactId>hamcrest-core</artifactId>
				<version>${hamcrest.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-contract-wiremock</artifactId>
				<version>${spring-cloud-contract-wiremock.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>no.nav.modig</groupId>
				<artifactId>modig-testcertificates</artifactId>
				<version>${modig-testcertificates.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>httpunit</groupId>
				<artifactId>httpunit</artifactId>
				<version>${httpunit.version}</version>
				<exclusions>
					<exclusion>
						<groupId>javax.servlet</groupId>
						<artifactId>servlet-api</artifactId>
					</exclusion>
				</exclusions>
				<scope>test</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<!-- Logging dependecies -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-logging</artifactId>
			<exclusions>
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- test -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-library</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-core</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-webdav-jackrabbit</artifactId>
				<version>1.0</version>
			</extension>
		</extensions>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M4</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>3.0.0-M4</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-toolchains-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<goals>
							<goal>toolchain</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<toolchains>
						<jdk>
							<version>11</version>
							<vendor>openjdk</vendor>
						</jdk>
					</toolchains>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>