package no.nav.regoppslag.consumer.pdl.to;

public enum AdresseKildeCode {
	BOSTEDSADRESSE,
	OPPHOLDSADRESSE,
	KONTAKTADRESSE,
	DELTBOSTED,
	KONTAKTINFORMASJONFORDØDSBO,
	ENHETPOSTADRESSE,
	ENHETFORRETNINGSADRESSE
}
