spring.profiles.include=nais, local
app.name="regoppslag"
APP_VERSION=0.0.0
logging.config=classpath:logback-local.xml

VIRKSOMHET_ORGANISASJON_V4_ENDPOINTURL=https://modapp-t8.adeo.no/ereg/ws/OrganisasjonService/v4
VIRKSOMHET_PERSON_V3_ENDPOINTURL=https://wasapp-t8.adeo.no/tpsws/ws/Person/v3
VIRKSOMHET_ORGANISASJONENHETKONTAKTINFORMASJON_V1_ENDPOINTURL=https://app-t8.adeo.no/norg2/ws/OrganisasjonEnhetKontaktinformasjon/v1
DOKUMENTTYPEINFO_V3_URL=https://app-t8.adeo.no/dokkat/rest/dokumenttypeinfo/v3
securityTokenService.url=https://sts-t8.test.local/SecurityTokenServiceProvider/
serviceuser.username=srvregoppslag
serviceuser.password=eQH0YB4u8ChZKC6
ldap_user_basedn=ou=NAV,ou=BusinessUnits,dc=test,dc=local
ldap_url=ldaps://ldapgw.test.local
ldap_username=srvSSOLinux
ldap_password=khFKL0GCusWe72
ldap_basedn=dc=test,dc=local
REDIS_HOST=rfs-regoppslag