# Spring
logging.config=classpath:logback-spring.xml
spring.main.banner_mode=off
spring.aop.auto=false
spring.jmx.enabled=false
server.tomcat.min-spare-threads=10
server.tomcat.max-threads=100
endpoints.prometheus.enabled=true
endpoints.prometheus.sensitive=false

applicationName=regoppslag
applicationVersion=@project.version@
bootstrapVersion=@bootstrap.version@
endpoints.enabled=false

# App properties
app.name=Registeroppslag
srvappserver_username=srvappserver
srvappserver_password=
SRVREGOPPSLAG_CERT_KEYSTOREALIAS=app-key
VIRKSOMHET_PERSON_V3_READTIMEOUTMS=10000
VIRKSOMHET_PERSON_V3_CONNECTTIMEOUTMS=3000
VIRKSOMHET_ORGANISASJON_V4_READTIMEOUTMS=10000
VIRKSOMHET_ORGANISASJON_V4_CONNECTTIMEOUTMS=3000
VIRKSOMHET_ORGANISASJONENHETKONTAKTINFORMASJON_V1_READTIMEOUTMS=10000
VIRKSOMHET_ORGANISASJONENHETKONTAKTINFORMASJON_V1_CONNECTTIMEOUTMS=3000
DOKUMENTTYPEINFO_V3_READTIMEOUTMS=3000
DOKUMENTTYPEINFO_V3_CONNECTTIMEOUTMS=3000

ldap.requiredroledn=cn=0000-GA-dokmot-api-skriv,ou=AccountGroups,ou=Groups,ou=NAV,ou=BusinessUnits