# Spring
logging.config=classpath:logback-nais.xml
spring.main.banner_mode=off
spring.aop.auto=false
spring.jmx.enabled=false
server.tomcat.threads.min-spare=10
server.tomcat.threads.max=100

###############################################
#                  Actuator                   #
###############################################
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.endpoint.caches.enabled=true
management.endpoints.enabled-by-default=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus,info,health,caches
management.health.redis.enabled=true

server.error.include-message=always

applicationName=regoppslag
applicationVersion=@project.version@
bootstrapVersion=@bootstrap.version@

# App properties
server.max-http-header-size=20000
srvappserver_username=srvappserver
srvappserver_password=
#todo remove
organisasjon-v4.readtimeoutms=10000
organisasjon-v4.connecttimeoutms=3000
organisasjonenhetkontaktinformasjon-v1.readtimeoutms=10000
organisasjonenhetkontaktinformasjon-v1.connecttimeoutms=3000
dokumenttypeinfo-v3.readtimeoutms=3000
dokumenttypeinfo-v3.connecttimeoutms=3000

redis.hostname=regoppslag-redis
redis.port=6379

#For only including the rest controllers in swagger
springdoc.packages-to-scan=no.nav.regoppslag.rest
#For sorting endpoints alphabetically
springdoc.swagger-ui.operationsSorter=alpha
#For sorting tags alphabetically
springdoc.swagger-ui.tagsSorter=alpha

# Azure
#no.nav.security.jwt.issuer.azurev2.accepted-audience=${AZURE_APP_CLIENT_ID}
#no.nav.security.jwt.issuer.azurev2.discovery-url=${AZURE_APP_WELL_KNOWN_URL}

http.proxy.parametername=notused