# Spring
logging.config=classpath:logback-spring.xml
spring.main.banner_mode=off
spring.aop.auto=false
spring.jmx.enabled=false
server.tomcat.min-spare-threads=10
server.tomcat.max-threads=100

applicationName=regoppslag
applicationVersion=@project.version@
bootstrapVersion=@bootstrap.version@
#endpoints.enabled=false
#endpoints.prometheus.enabled=true
#endpoints.prometheus.sensitive=false

# App properties
srvappserver_username=srvappserver
srvappserver_password=