spring.profiles.include=nais, local
namespace=q0

app.name="regoppslag"
APP_VERSION=0.0.0

logging.config=classpath:logback-local.xml
server.port=8080

virksomhet-organisasjon-v4.endpointurl=https://modapp-${namespace}.adeo.no/ereg/ws/OrganisasjonService/v4
virksomhet-person-v3.endpointurl=https://wasapp-${namespace}.adeo.no/tpsws/ws/Person/v3
virksomhet-organisasjonenhetkontaktinformasjon-v1.endpointurl=https://app-${namespace}.adeo.no/norg2/ws/OrganisasjonEnhetKontaktinformasjon/v1
dokumenttypeinfo-v3.url=https://app-${namespace}.adeo.no/dokkat/rest/dokumenttypeinfo/v3
securityTokenService.url=https://sts-${namespace}.preprod.local/SecurityTokenServiceProvider/
serviceuser.username=srvregoppslag
serviceuser.password=eQH0YB4u8ChZKC6
ldap_user_basedn=ou=NAV,ou=BusinessUnits,dc=test,dc=local
ldap_url=ldaps://ldapgw.test.local
ldap_username=srvSSOLinux
ldap_password=
ldap_basedn=dc=test,dc=local

