<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>no.nav.regoppslag</groupId>
		<artifactId>regoppslag</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>

	<artifactId>app</artifactId>
	<packaging>jar</packaging>
	<name>regoppslag :: App</name>

	<properties>
		<start-class>no.nav.regoppslag.Application</start-class>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.camel</groupId>
			<artifactId>camel-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>bootstrap</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.inject</groupId>
			<artifactId>javax.inject</artifactId>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
		</dependency>
		<!-- Prometheus client -->
		<dependency>
			<groupId>io.prometheus</groupId>
			<artifactId>simpleclient</artifactId>
			<version>${prometheus.version}</version>
		</dependency>
		<dependency>
			<groupId>io.prometheus</groupId>
			<artifactId>simpleclient_hotspot</artifactId>
			<version>${prometheus.version}</version>
		</dependency>
		<dependency>
			<groupId>io.prometheus</groupId>
			<artifactId>simpleclient_servlet</artifactId>
			<version>${prometheus.version}</version>
		</dependency>
		<dependency>
			<groupId>io.prometheus</groupId>
			<artifactId>simpleclient_pushgateway</artifactId>
			<version>${prometheus.version}</version>
		</dependency>
		<dependency>
			<groupId>io.prometheus</groupId>
			<artifactId>simpleclient_spring_boot</artifactId>
			<version>${prometheus.version}</version>
		</dependency>
		<dependency>
			<groupId>io.prometheus</groupId>
			<artifactId>simpleclient_spring_web</artifactId>
			<version>${prometheus.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.cxf</groupId>
			<artifactId>cxf-spring-boot-starter-jaxws</artifactId>
			<version>${cxf.version}</version>
		</dependency>
		<!-- modig -->
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-log-common</artifactId>
			<version>${modig-log-common.version}</version>
		</dependency>
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-security-ws</artifactId>
			<version>${modig-security.version}</version>
		</dependency>
		<dependency>
			<groupId>no.nav.modig</groupId>
			<artifactId>modig-security-loginmodule</artifactId>
			<scope>runtime</scope>
			<version>${modig-security.version}</version>
		</dependency>
		<!-- tjenester -->
		<dependency>
			<groupId>no.nav.tjenester</groupId>
			<artifactId>nav-person-v3-tjenestespesifikasjon</artifactId>
			<version>${nav-person-v3-tjenestespesifikasjon.version}</version>
			<classifier>jaxws</classifier>
		</dependency>
		<dependency>
			<groupId>no.nav.tjenester.fim</groupId>
			<artifactId>nav-fim-organisasjon-v4-tjenestespesifikasjon</artifactId>
			<version>${nav-fim-organisasjon-v4-tjenestespesifikasjon.version}</version>
			<classifier>jaxws</classifier>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<skip>false</skip>
					<fork>true</fork>
					<useTestClasspath>true</useTestClasspath>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
						<configuration>
							<finalName>regoppslag</finalName>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>dockerfile-maven-plugin</artifactId>
				<configuration>
					<repository>docker.adeo.no:5000/dok/regoppslag</repository>
					<tag>${project.version}</tag>
				</configuration>
				<executions>
					<execution>
						<phase>deploy</phase>
						<goals>
							<goal>build</goal>
							<goal>push</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>