kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: REGOPPSLAG_ENDPOINTS_NORG2_URL
      value: {{ REGOPPSLAG_ENDPOINTS_NORG2_URL }}
    - name: REGOPPSLAG_ENDPOINTS_EREG_URL
      value: {{ REGOPPSLAG_ENDPOINTS_EREG_URL }}
    - name: REGOPPSLAG_ENDPOINTS_PDL_URL
      value: {{ REGOPPSLAG_ENDPOINTS_PDL_URL }}
    - name: REGOPPSLAG_ENDPOINTS_PDL_SCOPE
      value: {{ REGOPPSLAG_ENDPOINTS_PDL_SCOPE }}
    - name: REGOPPSLAG_ENDPOINTS_DOKMET_URL
      value: {{ REGOPPSLAG_ENDPOINTS_DOKMET_URL }}
    - name: REGOPPSLAG_ENDPOINTS_DIGDIRKRRPROXY_URL
      value: {{ REGOPPSLAG_ENDPOINTS_DIGDIRKRRPROXY_URL }}
    - name: REGOPPSLAG_ENDPOINTS_DIGDIRKRRPROXY_SCOPE
      value: {{ REGOPPSLAG_ENDPOINTS_DIGDIRKRRPROXY_SCOPE }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE }}
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment.name={{ ENVIRONMENT }}"
  image: {{ image }}
  ingresses:
        {{#each INGRESSES}}
          - {{this }}
        {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 4
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 512Mi
  vault:
    enabled: true
  webproxy: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
    {{#each AZURE_IAC_RULES}}
        - application: {{app}}
          namespace: {{namespace}}
          cluster: {{cluster}}
    {{/each}}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki