kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: AZURE_APP_TOKEN_URL
      value: {{AZURE_APP_TOKEN_URL}}
    - name: AZURE_APP_SCOPEDIGDIRKRR
      value: {{AZURE_APP_SCOPEDIGDIRKRR}}
    - name: REGOPPSLAG_PROXY_HOST
      value: {{REGOPPSLAG_PROXY_HOST}}
    - name: REGOPPSLAG_PROXY_PORT
      value: "{{REGOPPSLAG_PROXY_PORT}}"
    - name: SECURITYTOKENSERVICE_URL
      value: {{ SECURITYTOKENSERVICE_URL }}
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: {{ SECURITY_TOKEN_SERVICE_TOKEN_URL }}
    - name: ORGANISASJONENHETKONTAKTINFORMASJON_V1_ENDPOINTURL
      value: {{ ORGANISASJONENHETKONTAKTINFORMASJON_V1_ENDPOINTURL }}
    - name: EREG_ORGANISASJON_SERVICE_URL
      value: {{ EREG_ORGANISASJON_SERVICE_URL }}
    - name: DOKUMENTTYPEINFO_V3_URL
      value: {{ DOKUMENTTYPEINFO_V3_URL }}
    - name: PDL_URL
      value: {{ PDL_URL }}
    - name: DIGDIR_KRR_PROXY_URL
      value: {{ DIGDIR_KRR_PROXY_URL }}
    {{#if AZURE_APP_CLIENT_ID}}
    {{#if AZURE_APP_WELL_KNOWN_URL}}
    - name: AZURE_APP_CLIENT_ID
      value: {{ AZURE_APP_CLIENT_ID }}
    - name: AZURE_APP_WELL_KNOWN_URL
      value: {{ AZURE_APP_WELL_KNOWN_URL }}
    {{/if}}
    {{/if}}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_DISCOVERYURL }}
    - name: NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE
      value: {{ NO_NAV_SECURITY_JWT_ISSUER_RESTSTS_ACCEPTED_AUDIENCE }}
  image: {{ image }}
  ingresses:
        {{#each INGRESSES}}
          - {{this }}
        {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 4
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVREGOPPSLAG }}
        mountPath: /var/run/secrets/nais.io/srvregoppslag
  webproxy: true
  azure:
    application:
      enabled: true
{{#if AZURE_IAC_RULES}}
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
      {{#each AZURE_IAC_RULES}}
        - application: {{app}}
          namespace: {{namespace}}
          cluster: {{cluster}}
      {{/each}}
{{/if}}