<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
		   elementFormDefault="qualified"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://nav.no/dok/pesysbrev/felles/v1/AdresseEnhet"
		   xmlns="http://nav.no/dok/pesysbrev/felles/v1/AdresseEnhet"
		   xmlns:norskpostadresse="http://nav.no/dok/pesysbrev/felles/v1/NorskPostadresse"
		   xmlns:st="http://nav.no/dok/pesysbrev/felles/v1/SimpleTypes"
		   xmlns:navenhet="http://nav.no/dok/pesysbrev/felles/v1/NavEnhet">

	<xs:import schemaLocation="v1.NavEnhet.xsd" namespace="http://nav.no/dok/pesysbrev/felles/v1/NavEnhet"/>
	<xs:import schemaLocation="v1.SimpleTypes.xsd" namespace="http://nav.no/dok/pesysbrev/felles/v1/SimpleTypes"/>
	<xs:import schemaLocation="v1.NorskPostadresse.xsd" namespace="http://nav.no/dok/pesysbrev/felles/v1/NorskPostadresse"/>

	<xs:complexType abstract="true" name="AdresseEnhet">
		<xs:annotation>
			<xs:documentation>En NAV-enhet med telefonnummer og adresse</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="navenhet:NavEnhet">
				<xs:sequence>
					<xs:element name="kontaktTelefonnummer" type="st:NonEmptyString"/>
					<xs:element name="adresse" type="norskpostadresse:NorskPostadresse"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>