<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
		   elementFormDefault="qualified"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://nav.no/dok/felles/v1/Besoksadresse"
		   xmlns="http://nav.no/dok/felles/v1/Besoksadresse"
		   xmlns:adresseenhet="http://nav.no/dok/felles/v1/AdresseEnhet">

	<xs:import schemaLocation="v1.AdresseEnhet.xsd" namespace="http://nav.no/dok/felles/v1/AdresseEnhet"/>

	<xs:complexType name="Besoksadresse">
		<xs:annotation>
			<xs:documentation>Gydig mottaker type</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="adresseenhet:AdresseEnhet"/>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>