<?xml version="1.0" encoding="UTF-8"?>
<xs:schema	attributeFormDefault="unqualified"
			  elementFormDefault="qualified"
			  xmlns:xs="http://www.w3.org/2001/XMLSchema"
			  targetNamespace="http://nav.no/dok/felles/v1/Kontaktinformasjon"
			  xmlns="http://nav.no/dok/felles/v1/Kontaktinformasjon"
			  xmlns:returadresse="http://nav.no/dok/felles/v1/Returadresse"
			  xmlns:besoksadresse="http://nav.no/dok/felles/v1/Besoksadresse"
			  xmlns:postadresse="http://nav.no/dok/felles/v1/Postadresse">

	<xs:import schemaLocation="v1.Returadresse.xsd" namespace="http://nav.no/dok/felles/v1/Returadresse"/>
	<xs:import schemaLocation="v1.Postadresse.xsd" namespace="http://nav.no/dok/felles/v1/Postadresse"/>
	<xs:import schemaLocation="v1.Besoksadresse.xsd" namespace="http://nav.no/dok/felles/v1/Besoksadresse"/>


	<xs:complexType name="Kontaktinformasjon">
		<xs:annotation>
			<xs:documentation>Informasjon om hvordan bruker kan kontakte NAV før å følge opp saken</xs:documentation>
		</xs:annotation>
		<xs:all>
			<xs:element name="returadresse" type="returadresse:Returadresse"/>
			<xs:element name="postadresse" type="postadresse:Postadresse"/>
			<xs:element name="besoksadresse" type="besoksadresse:Besoksadresse"/>
		</xs:all>
	</xs:complexType>

</xs:schema>