<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
		   elementFormDefault="qualified"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://nav.no/dok/felles/v1/NavAnsatt"
		   xmlns="http://nav.no/dok/felles/v1/NavAnsatt"
		   xmlns:st="http://nav.no/dok/felles/v1/SimpleTypes">

	<xs:import schemaLocation="v1.SimpleTypes.xsd" namespace="http://nav.no/dok/felles/v1/SimpleTypes"/>

	<xs:complexType name="NavAnsatt">
		<xs:annotation>
			<xs:documentation>Navn på ansatt i NAV</xs:documentation>
		</xs:annotation>
		<xs:all>
			<xs:element name="ansattId" type="st:Identifikator"/>
			<xs:element name="navn" type="st:NonEmptyString"/>
		</xs:all>
	</xs:complexType>
</xs:schema>