<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
		   elementFormDefault="qualified"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://nav.no/dok/pesysbrev/felles/v1/Saksbehandler"
		   xmlns="http://nav.no/dok/pesysbrev/felles/v1/Saksbehandler"
		   xmlns:na="http://nav.no/dok/pesysbrev/felles/v1/NavAnsatt"
		   xmlns:ne="http://nav.no/dok/pesysbrev/felles/v1/NavEnhet">

	<xs:import schemaLocation="v1.NavAnsatt.xsd" namespace="http://nav.no/dok/pesysbrev/felles/v1/NavAnsatt"/>
	<xs:import schemaLocation="v1.NavEnhet.xsd" namespace="http://nav.no/dok/pesysbrev/felles/v1/NavEnhet"/>

	<xs:complexType name="Saksbehandler">
		<xs:all>
			<xs:element name="navAnsatt" type="na:NavAnsatt"/>
			<xs:element name="navEnhet" type="ne:NavEnhet"/>
		</xs:all>
	</xs:complexType>
</xs:schema>